### ISSUE TITLE
[error] WASI-NN plugin not installed. Please install the plugin and restart WasmEdge.

### ISSUE THREAD

**Issue by mrljdx** [juntao/demo-object-detection#2]
- Hardware environment: 
  - Macbook Pro M3 Max
- Running environment: 
  - VSCode + Terminal
- Wasmedge version: 
  - 0.13.5
- Problem description: 
  - has according to the official document https://wasmedge.org/docs/develop/rust/wasinn/mediapipe installed WASI - NN Plugin with TensorFlow Lite.
  - cargo build is ok
    ```bash
    cargo build --target wasm32-wasi --release
    ```
    but execute the command reported an error
    ```bash
    wasmedge compile target/wasm32-wasi/release/demo-object-detection.wasm demo-object-detection.wasm
    ```
- Error info: 
[error] WASI-NN plugin not installed. Please install the plugin and restart WasmEdge.

Whether this demo can run on the M-series chips of Mac ?

**Comment by alabulei1** [comment]
Hi @mrljdx 

Sorry for the late reply. The WASI-NN plugin with TensorFlow Lite only works on Ubuntu OS now. You can try it on a Ubuntu machine.

**Comment by mrljdx** [comment]
@alabulei1 Thanks for your reply
